In [ ]:
import numpy as np

In [12]:
empty = np.empty((2 , 3))
print(empty)
print("------------")
print(empty[1])

[[5.05000238e-310 1.71215703e-052 1.77290800e+160]
 [4.46439186e-090 9.13151489e+169 6.58315227e-310]]
------------
[4.46439186e-090 9.13151489e+169 6.58315227e-310]


In [14]:
# This code will create an array for us.

a = np.arange(7)
# a
print(a)



[0 1 2 3 4 5 6]


In [21]:
# create an array which has the even numbers inside it

even = np.arange(2 , 21 , 2)
# even
print( " The array of even numbers =", even)

 The array of even numbers = [ 2  4  6  8 10 12 14 16 18 20]


In [23]:
# If you want to see some kind of linear sccend link between your array elements , then you can use linspace
lin_Space = np.linspace(2 , 30 ,  num=10)
lin_Space

# It is showing the linear trend in a particular discipline

array([ 2.        ,  5.11111111,  8.22222222, 11.33333333, 14.44444444,
       17.55555556, 20.66666667, 23.77777778, 26.88888889, 30.        ])

# How we can concatenate Two Different Arrays Using Numpy

In [28]:
arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([3, 5 , 8 , 0 , 6 , 13])

concatenate = np.concatenate((arr1 , arr2))
concatenate

array([ 1,  2,  3,  4,  5,  6,  3,  5,  8,  0,  6, 13])

# Concatenating 2D Arrays

In [49]:
twoD_Arr1 = np.array([[3 , 4 , 5 , 6] , [2 , 3 , 1 ,4]])
twoD_Arr1
print("Shape = " , twoD_Arr1.shape)
twoD_Arr2 = np.array([[45 , 89 , 32 , 13] , [3 , 90 , 42 , 34]])

concat = np.concatenate((twoD_Arr1 , twoD_Arr2) , axis = 1) # 'axis=1' is used to concatenate two D arrays with each other
print(concat)
print("The length is ->" ,len(concat))

Shape =  (2, 4)
[[ 3  4  5  6 45 89 32 13]
 [ 2  3  1  4  3 90 42 34]]
The length is -> 2


# 3D Array

In [44]:
# Creating a 3D Array
array3D_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])

len(array3D_example)


3

In [59]:
shape = array3D_example.shape
print("The shape of this array is =" , shape)
print("The dimension of this array is",array3D_example.ndim)

The shape of this array is = (3, 2, 4)
The dimension of this array is 3


In [77]:
# We can also reshape an arrray by writing the code:

shape = array3D_example.reshape(3 , 2 , 4)
print(shape)

[[[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]]
