In [2]:
# NumPy In Detail :

# What actually is Array: An Array is a data structure , which is used to store different data types variables in a single variable collectively
# In our Numpy , we use Array just for the sake of data analysis , machine learning and to save different data in python
# NumPy is an abbreviation of Numerical Python

In [31]:
# Importing the Library

import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [15]:
# np.arange(6)
a = np.arange(9)
print(a)

# Here we can say that it is one dimensional array.

# If I want to print the dimensions then:
a.shape # Here, we have to say that , there are no rows or columns are present , it is only called as (values) Like , we will say that there are 09 values in this array
# Always keep it in your mind that we can't count the rows and columns when the array is one dimensional

[0 1 2 3 4 5 6 7 8]


(9,)

In [13]:
a2 = a[np.newaxis, :]
print(a2)

# Here we can say that it is two dimensional array

[[0 1 2 3 4 5 6 7 8]]


In [22]:
a_ = a[ np.newaxis, : ]
print(a_)

[[0 1 2 3 4 5 6 7 8]]


In [24]:
a3 = a_[np.newaxis , : ]
print(a3) # 3 dimensions array

[[[0 1 2 3 4 5 6 7 8]]]


In [ ]:
# # Assignment Question: Why do we use 1D , 2D and 3D arrays in NumPy

# 1. **1D Arrays:**
#    - **Use:** Think of it like a list of numbers. When you just have a single line of data, like a series of temperatures or scores, a 1D array is handy.
#    - **Example:** `[1, 2, 3, 4, 5]`

# 2. **2D Arrays:**
#    - **Use:** Imagine a grid or a table. When your data needs rows and columns, like a spreadsheet or a chessboard, 2D arrays come in. It's like having several lists arranged in a grid.
#    - **Example:**
#      ```
#      [[1, 2, 3],
#       [4, 5, 6],
#       [7, 8, 9]]
#      ```

# 3. **3D Arrays:**
#    - **Use:** If you need to organize data in a cube or a stack of tables, that's where 3D arrays shine. It's like having multiple spreadsheets, each with rows and columns, and stacking them up.
#    - **Example:**
#      ```
#      [[[1, 2, 3],
#        [4, 5, 6]],

#       [[7, 8, 9],
#        [10, 11, 12]],

#       [[13, 14, 15],
#        [16, 17, 18]]]
#      ```

# In a nutshell, 1D is like a line, 2D is like a table, and 3D is like a stack of tables. Different shapes for different types of data! NumPy allows us to work with these arrays efficiently in Python.

# Creating Arrays With NumPy:

**Let's start creating 1D , 2D or 3D Arrays in Python NumPy**


In [25]:
arr = np.array([3,4,5,6])
print(arr)

[3 4 5 6]


In [39]:
arr_two_dimension = np.array([(3,4,5,6) , (9 , 3 , 2 ,1 ),  (9 , 3 , 2 ,1 ) , (9 , 3 , 2 ,1 )])
# print(arr_two_dimension)

# Now if I wanna check the dimensions of 1D & 2D Array , then we will just look at the following method

arr.shape

(4,)

In [40]:
arr_two_dimension.shape # There are 04 rows and 04 columns which are here in our two dimension array

(4, 4)

In [41]:
print (arr)
arr.shape

[3 4 5 6]


(4,)

In [42]:
print(arr_two_dimension)
arr_two_dimension.shape


[[3 4 5 6]
 [9 3 2 1]
 [9 3 2 1]
 [9 3 2 1]]


(4, 4)

# Initialize Arrays:


In [51]:
zeros = np.zeros((1,5)) # (rows , column)
zeros # There are 05 rows and 01 columns present here in our output

array([[0., 0., 0., 0., 0.]])

In [52]:
# If you want to see one , then you will write

ones = np.ones((5, 4))
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [56]:
# Note: If you ever wanna fill your array values with different numbers , then you can write the syntax as

full = np.full((4,6) , 9 ) # 09 was my desired number and we have filled this array with this number as per my desire
full

array([[9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9]])

In [61]:
# Making an identity matrix
identity = np.eye(8) # this is the identity matrix here we can see that there are total 08 rows and 08 columns
identity

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [ ]:
# Note:

a.type # It will tell me about the data
a.dtype #It will tell me about the data type of (a)

# Array Attributes

In [70]:
# It gives us the dimension of an array

a.ndim


1

In [69]:
# It gives us the length of array elements in an array

len(a)


9

In [63]:
# You can find out the rows and columns of your array:

a.shape


(9,)

In [68]:
a.size # It gives us the number of elements in an array

9

# Bais Operations of an Array

In [71]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [84]:
b = np.arange(9)

b

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [86]:
operation = a + b
operation

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16])

In [95]:
print ( "The array 'a' is =  ", a)
print ( "The array 'b' is =  ", b)


The array 'a' is =   [0 1 2 3 4 5 6 7 8]
The array 'b' is =   [0 1 2 3 4 5 6 7 8]


In [89]:
# There is another method of adding two arrays using NumPy

operation = np.add(a,b)
operation

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16])

In [94]:
print ( "The array 'a' is =  ", a)
print ( "The array 'b' is =  ", b)


The array 'a' is =   [0 1 2 3 4 5 6 7 8]
The array 'b' is =   [0 1 2 3 4 5 6 7 8]


In [90]:
# For Subtraction:

minus = np.subtract(a, b) # Through this we can subtract
minus

array([0, 0, 0, 0, 0, 0, 0, 0, 0])

In [93]:
print ( "The array 'a' is =  ", a)
print ( "The array 'b' is =  ", b)


The array 'a' is =   [0 1 2 3 4 5 6 7 8]
The array 'b' is =   [0 1 2 3 4 5 6 7 8]


In [98]:
# For Multiplication:

Multiply = np.multiply(a, b) # Through this we can subtract
Multiply

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64])

In [97]:
# For Divisioon:

division = np.divide(a, b) # Through this we can subtract
division

array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [99]:
# If we want to find out the power of any specific numbers in an array , then we can also find it out using:

find_power = np.power(4 , 2)
find_power

16

In [101]:
print ( "The array 'a' is =  ", a)
print ( "The array 'b' is =  ", b)


The array 'a' is =   [0 1 2 3 4 5 6 7 8]
The array 'b' is =   [0 1 2 3 4 5 6 7 8]


In [102]:
# An extra thing , you can also find out the power of an array element using this method:

power = 4 ** 4
power

256