#**Marix Or Matrices in Numpy**

In [ ]:
import numpy as np

In [ ]:
# Create a matrix of 2x3 in numpy

a = np.array([[4, 5, 2] , [7 ,8 , 9]])
a # It is a matrix who has two rows and three columns

array([[4, 5, 2],
       [7, 8, 9]])

In [ ]:
b = np.arange(0 , 100 ,2 )
b # Now all these values are not in matrix
b.shape

(50,)

In [ ]:
# We can reshape all these indexes , in order to convert it into an array

b = b.reshape(10,5)
b

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48],
       [50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68],
       [70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88],
       [90, 92, 94, 96, 98]])

---
# Slicing a Matrix using NumPy

In [ ]:
# Slicing a matrix of 3x2

# b[2:3 , 3:5]

b[1:4 , 2:3]

array([[14],
       [24],
       [34]])

In [ ]:
# This code will print all the columns and all the rows

c = b[:,:]
c

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48],
       [50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68],
       [70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88],
       [90, 92, 94, 96, 98]])

In [ ]:
# To find the maximum from the matrix

c = b.max()
print(c)
# for minimun
minimum = b.min()
minimum

98


0

In [ ]:
# to find the sum of whole matrix values

sum = c.sum()
sum

2450

In [ ]:
# note: { axis = 0 } means that we are talking about the row

In [ ]:
# note: { axis = 1 } means that we are talking about the column