# Creating Numpy Arrays from Existing Data

In [1]:
import numpy as np

In [2]:
array1 = np.arange(1 , 50 , 2)
array1

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49])

In [3]:
len(array1)

25

In [7]:
array1[22:25]
array1[24]

49

In [12]:
# Now let's talk about horizontal and vertical stack

a=np.array((1,2,3,4,5))
b= np.array((6,7,8,9,10))
c = np.vstack((a,b))

c  # our array have been vertically stacked here

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [13]:
# our array have been vertically stacked here

c = np.hstack((a,b))
c

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
# For Example , if I want to reshape this array then

reshaped = c.reshape(2,5)

reshaped

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])