# NumPy Indexing & Slicing

In [1]:
import numpy as np

In [4]:
arr = np.arange(4)
# print(arr)
arr

# we have printed an array here


array([0, 1, 2, 3])

In [14]:
# If I want to index them .

array = np.arange(1 , 12 , 2)
print(array)
array[3]

[ 1  3  5  7  9 11]


7

In [16]:
c = array.reshape(2,3)
c # I have reshaped an array into 2D

array([[ 1,  3,  5],
       [ 7,  9, 11]])

In [17]:
d = array.reshape(3,2)
d # The array has been reshaped , into 2 columns and 3 rows

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])

In [19]:
d[2]
d[0]

array([1, 3])

In [27]:
# If I want to print some specific quantity elements from myarray , then I will code like this:

a = np.arange(0,8)
print("complete Array = " , a)
print("The array elements smaller than 2 are" ,a[a<2])

complete Array =  [0 1 2 3 4 5 6 7]
The array elements smaller than 2 are [0 1]


In [ ]:
# We have also discussed about arithmetic and logical operators in detail

In [ ]:
# AND TILL YET WE HAVE DISCUSSED IN DETAIL ABOUT INDEXING AND SLICING OF NUMPY ARRAYS